wifi_ssid: "YOUR_WIFI_NAME"
wifi_password: "YOUR_WIFI_PASSWORD"

midea_air_api_key: "PASTE_ESPHOME_API_ENCRYPTION_KEY_HERE"
midea_air_ota_password: "PASTE_OTA_PASSWORD_HERE"
midea_air_fallback_password: "12345678"
